#!/bin/bash
# Script envoltorio para cumplir con el nombre exacto de ejecutable ./vaccine

# Aseguramos que la raiz del módulo sea visible para las importaciones
export PYTHONPATH="$(pwd):$PYTHONPATH"

# Activamos el entorno si existe
if [ -d "venv" ]; then
    source venv/bin/activate
fi

python3 src/vaccine.py "$@"